#!/bin/sh
mkdir -p pichayon/web/static/brython_modules/
poetry run brython-cli update --update-dir pichayon/web/static/brython_modules/


BRYTHON_ID=$(pgrep -f $(pwd)/scripts/auto-build-brython);

if [ ! -z "$BRYTHON_ID" ]
then
	echo "brython allready run kill!!"
	kill -KILL $BRYTHON_ID
fi

poetry run python $(pwd)/scripts/auto-build-brython &


PICHAYON_SETTINGS=$(pwd)/pichayon-development.cfg poetry run pichayon-web -d
